name: Deploy Artifact

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version'
        required: false
        default: "16"
        type: string
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
    secrets:
      server-username:
        required: true
      server-password:
        required: true
      deploy-secret-key:
        required: true
      deploy-secret-key-password:
        required: true
      github-token:
        required: true
      mm-webhook-url:
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Bundle specification
        run: npm run build

      - name: Validate specification
        run: npm run validate

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            web_deploy
          key: ${{ runner.os }}-web-${{ github.sha }}

  deploy-server:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            web_deploy
          key: ${{ runner.os }}-web-${{ github.sha }}

      - name: Retrieve commit info
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: commit_info

      - name: Set artifact version
        run: |
          mvn versions:set versions:commit -DnewVersion="1.${{ steps.commit_info.outputs.COMMIT_NUMBER }}-${{ steps.commit_info.outputs.SHA_7 }}-server"

      - name: Deploy server package
        uses: valitydev/action-deploy-jdk-package@v1.0.13
        with:
          jdk-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          server-username: ${{ secrets.server-username }}
          server-password: ${{ secrets.server-password }}
          deploy-secret-key: ${{ secrets.deploy-secret-key }}
          deploy-secret-key-password: ${{ secrets.deploy-secret-key-password }}
          maven-args: '-Dcommit.number=${{ steps.commit_info.outputs.COMMIT_NUMBER }} -Drevision="1.${{ steps.commit_info.outputs.COMMIT_NUMBER }}-${{ steps.commit_info.outputs.SHA_7 }}-server" -P="server"'

  deploy-client:
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            web_deploy
          key: ${{ runner.os }}-web-${{ github.sha }}

      - name: Retrieve commit info
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: commit_info

      - name: Set artifact version
        run: |
          mvn versions:set versions:commit -DnewVersion="1.${{ steps.commit_info.outputs.COMMIT_NUMBER }}-${{ steps.commit_info.outputs.SHA_7 }}-client"

      - name: Deploy client package
        uses: valitydev/action-deploy-jdk-package@v1.0.13
        with:
          jdk-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          server-username: ${{ secrets.server-username }}
          server-password: ${{ secrets.server-password }}
          deploy-secret-key: ${{ secrets.deploy-secret-key }}
          deploy-secret-key-password: ${{ secrets.deploy-secret-key-password }}
          maven-args: '-Dcommit.number=${{ steps.commit_info.outputs.COMMIT_NUMBER }} -Drevision="1.${{ steps.commit_info.outputs.COMMIT_NUMBER }}-${{ steps.commit_info.outputs.SHA_7 }}-client" -P="client"'

  publish-redoc:
    runs-on: ubuntu-20.04
    needs: [ deploy-client, deploy-server ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            web_deploy
          key: ${{ runner.os }}-web-${{ github.sha }}

      - name: Build static html
        run: |
          npx redoc-cli bundle web_deploy/openapi.yaml
          mv redoc-static.html index.html

      - name: Publish ReDoc on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github-token }}
          publish_dir: .
          force_orphan: true
          exclude_assets: '.github,openapi,plugins,web,.redocly.yaml,LICENSE,README.md,pom.xml,renovate.json,package.json,package-lock.json'

  success-notify:
    runs-on: ubuntu-20.04
    needs: [deploy-server, deploy-client]
    if: success()
    steps:
      - name: Mattermost Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: "#00c100"
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""

  fail-notify:
    runs-on: ubuntu-20.04
    needs: [deploy-server, deploy-client]
    if: failure()
    steps:
      - name: Mattermost Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: "#e40303"
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""
