name: Maven Deploy Artifact

on:
  workflow_call:
    secrets:
      github-token:
        required: true
      mm-webhook-url:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7

      - name: Deploy image
        uses: valitydev/action-deploy-docker@v1.0.16
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.github-token }}

  test-coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7

      - name: Upload code coverage
        uses: codecov/codecov-action@v1

  notify:
    runs-on: ubuntu-20.04
    needs: build-and-deploy
    steps:
      - name: Mattermost Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: ${{ github.event.repository.name }}
          SLACK_WEBHOOK: ${{ secrets.mm-webhook-url }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""