name: Maven Build Artifact

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7

  test-coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Build Java
        uses: valitydev/action-jdk-build@v0.0.7

      - name: Upload code coverage
        uses: codecov/codecov-action@v1