name: Maven Build Artifact

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build package
        run: mvn --batch-mode clean compile
  code-coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Upload code coverage
        uses: codecov/codecov-action@v1