name: Maven Deploy Artifact

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout GitHub Action JDK Build Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-jdk-build
          ref: v0.0.7
          path: .github/actions/action-jdk-build

      - name: Checkout GitHub Action Deploy Docker Repo
        uses: actions/checkout@v2
        with:
          repository: valitydev/action-deploy-docker
          ref: v1.0.16
          path: .github/actions/action-deploy-docker

      - name: Run Build Java
        uses: ./.github/actions/action-jdk-build

      - name: Test Coverage
        uses: codecov/codecov-action@v1

      - name: Deploy image
        uses: ./.github/actions/action-deploy-docker
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.github-token }}