name: Run Semgrep
on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: | 
          semgrep \
            --json --output semgrep.json \
            --metrics=off \
            --config="p/default"

      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep_result
          path: semgrep.json

      - name: Check & Update/Create PR
        id: pr-check
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: | 
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            const branchName = context.ref.replace('refs/heads/', '');
            let pr = pullRequests.find(pr => pr.head.ref === branchName);
            if (!pr) {
              const { data: newPr } = await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Semgrep results for ${branchName}`,
                head: branchName,
                base: 'master', // Update to your default branch
                body: 'This PR contains Semgrep analysis results.',
              });
              pr = newPr;
            }
            core.setOutput("prNumber", pr.number);
              
      - name: Add Comment with Semgrep Results
        if: steps.pr-check.outputs.prNumber != 'null'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const semgrepResults = fs.readFileSync('semgrep.json', 'utf8');
            const prNumber = "${{ steps.pr-check.outputs.prNumber }}";
            await github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Semgrep analysis results:\n\`\`\`json\n${semgrepResults}\n\`\`\``,
               });